version: '3.8'

services:
  blog-db-postgres:
    container_name: blog-db-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog_db
    volumes:
      - postgres_blog_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network

  blog-api:
    container_name: blog-api
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - blog-db-postgres
    environment:
      DATABASE_URL: "postgresql://postgres:password@blog-db-postgres:5432/blog_db?schema=public"
      JWT_SECRET_KEY: "jwt-secret-key"
    command: [ "pnpm", "run", "start:prod" ]
    networks:
      - app-network

volumes:
  postgres_blog_data:
    driver: local

networks:
  app-network:
    driver: bridge
